name: Update data
on:
  push:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
jobs:
  pandotronic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #        with:
      #          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install
        run: |
          pip install prettytable

      - name: Fetch bantz
        run: |
          wget https://hugovk.neocities.org/watsoncomedy.txt -O data/chat.txt
          ls -l

      - name: Count 'em
        run: |
          python countem.py -i data/chat.txt --words hype,pando,baker,clap,turnip,mustard,swan,"mustard on a swan",chorizo,bsl
          ls -l data

      - name: Commit
        run: |
          git config --global user.email "watsonabot@example.com"
          git config --global user.name "Watsonabot"
          git add data
          git commit -m "Automatic hypes update!" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
