name: Update data
on:
  push:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:
jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #        with:
      #          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install
        run: |
          pip install tcd

      - name: Fetch log
        run: |
          tcd --quiet --video 609400064 --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }}
          ls -l

      - name: Count em
        run: |
          python countem.py --video 609400064

#          git config --global user.email "watsonabot@example.com"
#          git config --global user.name "Watsonabot"
#          git add *.txt
#          git commit -m "Automatic hypes update"
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}
